export const CATEGORIES = {
  code: { label: 'Code', color: '#e3b341' },
  markup: { label: 'Markup & Config', color: '#79c0ff' },
  data: { label: 'Data', color: '#56d4a4' },
  docs: { label: 'Documents', color: '#60a5fa' },
  spreadsheet: { label: 'Spreadsheets', color: '#34d399' },
  presentation: { label: 'Presentations', color: '#fb923c' },
  ebook: { label: 'Ebooks', color: '#a78bfa' },
  image: { label: 'Images', color: '#2dd4bf' },
  design: { label: 'Design files', color: '#f472b6' },
  audio: { label: 'Audio', color: '#f472b6' },
  video: { label: 'Video', color: '#fb7185' },
  archive: { label: 'Archives', color: '#facc15' },
  package: { label: 'Installers & packages', color: '#9ca3af' },
  font: { label: 'Fonts', color: '#c084fc' },
  cad3d: { label: '3D & CAD', color: '#38bdf8' },
  database: { label: 'Databases', color: '#22d3ee' },
  cert: { label: 'Certificates & keys', color: '#94a3b8' },
  email: { label: 'Email', color: '#93c5fd' },
  other: { label: 'Other', color: '#9ca3af' },
};

const NOPREVIEW_NOTES = {
  docs: 'Open this in Word, LibreOffice, or Google Docs.',
  spreadsheet: 'Open this in Excel, Numbers, or Google Sheets.',
  presentation: 'Open this in PowerPoint, Keynote, or Google Slides.',
  ebook: 'Open this in a dedicated ebook reader (Kindle, Apple Books, Calibre).',
  image: 'This image format has limited browser support. Open it in a photo app or converter.',
  design: 'Open this in the design app it came from (Photoshop, Illustrator, Figma, Sketch, XD).',
  audio: 'This audio format is not natively playable in the browser.',
  archive: 'Extract this with a file manager, 7-Zip, or WinRAR.',
  package: 'This is an installer or executable, not something to preview.',
  cad3d: 'Open this in a 3D or CAD application (Blender, AutoCAD, FreeCAD).',
  database: 'Open this with a database browser or the tool that produced it.',
  cert: 'This is a binary certificate or keystore, open it with a certificate manager.',
  email: 'Open this in a desktop email client, or convert it to .eml.',
  other: 'No preview is available for this file type yet.',
};

export function noPreviewNote(category) {
  return NOPREVIEW_NOTES[category] || NOPREVIEW_NOTES.other;
}

const FILENAME_OVERRIDES = {
  dockerfile: { kind: 'code', category: 'code', lang: 'dockerfile' },
  makefile: { kind: 'code', category: 'code', lang: 'text' },
  rakefile: { kind: 'code', category: 'code', lang: 'ruby' },
  gemfile: { kind: 'code', category: 'code', lang: 'ruby' },
  'gemfile.lock': { kind: 'code', category: 'code', lang: 'text' },
  'cmakelists.txt': { kind: 'code', category: 'code', lang: 'cmake' },
  license: { kind: 'code', category: 'code', lang: 'text' },
  readme: { kind: 'code', category: 'code', lang: 'text' },
  '.gitignore': { kind: 'code', category: 'markup', lang: 'text' },
  '.gitattributes': { kind: 'code', category: 'markup', lang: 'text' },
  '.npmrc': { kind: 'code', category: 'markup', lang: 'properties' },
  '.editorconfig': { kind: 'code', category: 'markup', lang: 'properties' },
  '.env': { kind: 'code', category: 'markup', lang: 'properties' },
  '.htaccess': { kind: 'code', category: 'markup', lang: 'properties' },
};

const EXT_MAP = {
  js: { kind: 'code', category: 'code', lang: 'javascript' },
  jsx: { kind: 'code', category: 'code', lang: 'javascript' },
  mjs: { kind: 'code', category: 'code', lang: 'javascript' },
  cjs: { kind: 'code', category: 'code', lang: 'javascript' },
  ts: { kind: 'code', category: 'code', lang: 'typescript' },
  tsx: { kind: 'code', category: 'code', lang: 'typescript' },
  vue: { kind: 'code', category: 'code', lang: 'vue' },
  svelte: { kind: 'code', category: 'code', lang: 'html' },
  liquid: { kind: 'code', category: 'code', lang: 'liquid' },
  py: { kind: 'code', category: 'code', lang: 'python' },
  pyw: { kind: 'code', category: 'code', lang: 'python' },
  pyi: { kind: 'code', category: 'code', lang: 'python' },
  java: { kind: 'code', category: 'code', lang: 'java' },
  kt: { kind: 'code', category: 'code', lang: 'kotlin' },
  kts: { kind: 'code', category: 'code', lang: 'kotlin' },
  scala: { kind: 'code', category: 'code', lang: 'scala' },
  sc: { kind: 'code', category: 'code', lang: 'scala' },
  groovy: { kind: 'code', category: 'code', lang: 'groovy' },
  gradle: { kind: 'code', category: 'code', lang: 'groovy' },
  c: { kind: 'code', category: 'code', lang: 'c' },
  h: { kind: 'code', category: 'code', lang: 'c' },
  cpp: { kind: 'code', category: 'code', lang: 'cpp' },
  cc: { kind: 'code', category: 'code', lang: 'cpp' },
  cxx: { kind: 'code', category: 'code', lang: 'cpp' },
  hpp: { kind: 'code', category: 'code', lang: 'cpp' },
  hh: { kind: 'code', category: 'code', lang: 'cpp' },
  cs: { kind: 'code', category: 'code', lang: 'csharp' },
  go: { kind: 'code', category: 'code', lang: 'go' },
  rs: { kind: 'code', category: 'code', lang: 'rust' },
  rb: { kind: 'code', category: 'code', lang: 'ruby' },
  erb: { kind: 'code', category: 'code', lang: 'ruby' },
  php: { kind: 'code', category: 'code', lang: 'php' },
  phtml: { kind: 'code', category: 'code', lang: 'php' },
  swift: { kind: 'code', category: 'code', lang: 'swift' },
  dart: { kind: 'code', category: 'code', lang: 'dart' },
  lua: { kind: 'code', category: 'code', lang: 'lua' },
  pl: { kind: 'code', category: 'code', lang: 'perl' },
  pm: { kind: 'code', category: 'code', lang: 'perl' },
  r: { kind: 'code', category: 'code', lang: 'r' },
  jl: { kind: 'code', category: 'code', lang: 'julia' },
  hs: { kind: 'code', category: 'code', lang: 'haskell' },
  lhs: { kind: 'code', category: 'code', lang: 'haskell' },
  clj: { kind: 'code', category: 'code', lang: 'clojure' },
  cljs: { kind: 'code', category: 'code', lang: 'clojure' },
  cljc: { kind: 'code', category: 'code', lang: 'clojure' },
  erl: { kind: 'code', category: 'code', lang: 'erlang' },
  hrl: { kind: 'code', category: 'code', lang: 'erlang' },
  ex: { kind: 'code', category: 'code', lang: 'text' },
  exs: { kind: 'code', category: 'code', lang: 'text' },
  ml: { kind: 'code', category: 'code', lang: 'ocaml' },
  mli: { kind: 'code', category: 'code', lang: 'ocaml' },
  fs: { kind: 'code', category: 'code', lang: 'fsharp' },
  fsx: { kind: 'code', category: 'code', lang: 'fsharp' },
  fsi: { kind: 'code', category: 'code', lang: 'fsharp' },
  sml: { kind: 'code', category: 'code', lang: 'sml' },
  pas: { kind: 'code', category: 'code', lang: 'pascal' },
  pp: { kind: 'code', category: 'code', lang: 'pascal' },
  vb: { kind: 'code', category: 'code', lang: 'vb' },
  vbs: { kind: 'code', category: 'code', lang: 'vbscript' },
  ps1: { kind: 'code', category: 'code', lang: 'powershell' },
  psm1: { kind: 'code', category: 'code', lang: 'powershell' },
  psd1: { kind: 'code', category: 'code', lang: 'powershell' },
  bat: { kind: 'code', category: 'code', lang: 'text' },
  cmd: { kind: 'code', category: 'code', lang: 'text' },
  sh: { kind: 'code', category: 'code', lang: 'shell' },
  bash: { kind: 'code', category: 'code', lang: 'shell' },
  zsh: { kind: 'code', category: 'code', lang: 'shell' },
  ksh: { kind: 'code', category: 'code', lang: 'shell' },
  fish: { kind: 'code', category: 'code', lang: 'shell' },
  sql: { kind: 'code', category: 'code', lang: 'sql' },
  ddl: { kind: 'code', category: 'code', lang: 'sql' },
  dml: { kind: 'code', category: 'code', lang: 'sql' },
  graphql: { kind: 'code', category: 'code', lang: 'text' },
  gql: { kind: 'code', category: 'code', lang: 'text' },
  proto: { kind: 'code', category: 'code', lang: 'protobuf' },
  asm: { kind: 'code', category: 'code', lang: 'gas' },
  s: { kind: 'code', category: 'code', lang: 'gas' },
  d: { kind: 'code', category: 'code', lang: 'd' },
  cr: { kind: 'code', category: 'code', lang: 'crystal' },
  zig: { kind: 'code', category: 'code', lang: 'text' },
  nim: { kind: 'code', category: 'code', lang: 'text' },
  v: { kind: 'code', category: 'code', lang: 'verilog' },
  sv: { kind: 'code', category: 'code', lang: 'verilog' },
  svh: { kind: 'code', category: 'code', lang: 'verilog' },
  vhd: { kind: 'code', category: 'code', lang: 'vhdl' },
  vhdl: { kind: 'code', category: 'code', lang: 'vhdl' },
  tcl: { kind: 'code', category: 'code', lang: 'tcl' },
  scm: { kind: 'code', category: 'code', lang: 'scheme' },
  ss: { kind: 'code', category: 'code', lang: 'scheme' },
  rkt: { kind: 'code', category: 'code', lang: 'scheme' },
  lisp: { kind: 'code', category: 'code', lang: 'commonlisp' },
  lsp: { kind: 'code', category: 'code', lang: 'commonlisp' },
  m: { kind: 'code', category: 'code', lang: 'objectivec' },
  mm: { kind: 'code', category: 'code', lang: 'objectivec' },
  f: { kind: 'code', category: 'code', lang: 'fortran' },
  f90: { kind: 'code', category: 'code', lang: 'fortran' },
  f95: { kind: 'code', category: 'code', lang: 'fortran' },
  for: { kind: 'code', category: 'code', lang: 'fortran' },
  cob: { kind: 'code', category: 'code', lang: 'cobol' },
  cbl: { kind: 'code', category: 'code', lang: 'cobol' },
  adb: { kind: 'code', category: 'code', lang: 'text' },
  ads: { kind: 'code', category: 'code', lang: 'text' },
  coffee: { kind: 'code', category: 'code', lang: 'coffeescript' },
  ls: { kind: 'code', category: 'code', lang: 'livescript' },
  tf: { kind: 'code', category: 'code', lang: 'text' },
  tfvars: { kind: 'code', category: 'code', lang: 'text' },
  sol: { kind: 'code', category: 'code', lang: 'text' },
  mk: { kind: 'code', category: 'code', lang: 'text' },
  wat: { kind: 'code', category: 'code', lang: 'wast' },
  fasta: { kind: 'code', category: 'data', lang: 'text' },
  fa: { kind: 'code', category: 'data', lang: 'text' },
  fastq: { kind: 'code', category: 'data', lang: 'text' },
  pdb: { kind: 'code', category: 'data', lang: 'text' },

  html: { kind: 'code', category: 'markup', lang: 'html' },
  htm: { kind: 'code', category: 'markup', lang: 'html' },
  xhtml: { kind: 'code', category: 'markup', lang: 'html' },
  jsp: { kind: 'code', category: 'markup', lang: 'html' },
  asp: { kind: 'code', category: 'markup', lang: 'html' },
  aspx: { kind: 'code', category: 'markup', lang: 'html' },
  xml: { kind: 'code', category: 'markup', lang: 'xml' },
  xsl: { kind: 'code', category: 'markup', lang: 'xml' },
  xslt: { kind: 'code', category: 'markup', lang: 'xml' },
  xsd: { kind: 'code', category: 'markup', lang: 'xml' },
  plist: { kind: 'code', category: 'markup', lang: 'xml' },
  rss: { kind: 'code', category: 'markup', lang: 'xml' },
  atom: { kind: 'code', category: 'markup', lang: 'xml' },
  gpx: { kind: 'code', category: 'data', lang: 'xml' },
  kml: { kind: 'code', category: 'data', lang: 'xml' },
  css: { kind: 'code', category: 'markup', lang: 'css' },
  scss: { kind: 'code', category: 'markup', lang: 'sass' },
  less: { kind: 'code', category: 'markup', lang: 'less' },
  styl: { kind: 'code', category: 'markup', lang: 'stylus' },
  json: { kind: 'json', category: 'markup' },
  json5: { kind: 'json', category: 'markup' },
  jsonc: { kind: 'json', category: 'markup' },
  webmanifest: { kind: 'json', category: 'markup' },
  jsonl: { kind: 'json', category: 'data' },
  ndjson: { kind: 'json', category: 'data' },
  geojson: { kind: 'json', category: 'data' },
  map: { kind: 'json', category: 'data' },
  yaml: { kind: 'code', category: 'markup', lang: 'yaml' },
  yml: { kind: 'code', category: 'markup', lang: 'yaml' },
  toml: { kind: 'code', category: 'markup', lang: 'toml' },
  ini: { kind: 'code', category: 'markup', lang: 'properties' },
  cfg: { kind: 'code', category: 'markup', lang: 'properties' },
  conf: { kind: 'code', category: 'markup', lang: 'properties' },
  properties: { kind: 'code', category: 'markup', lang: 'properties' },
  env: { kind: 'code', category: 'markup', lang: 'properties' },
  csv: { kind: 'csv', category: 'data' },
  tsv: { kind: 'csv', category: 'data' },
  md: { kind: 'markdown', category: 'docs' },
  markdown: { kind: 'markdown', category: 'docs' },
  mdx: { kind: 'markdown', category: 'docs' },
  tex: { kind: 'code', category: 'docs', lang: 'stex' },
  latex: { kind: 'code', category: 'docs', lang: 'stex' },
  rst: { kind: 'code', category: 'docs', lang: 'text' },
  adoc: { kind: 'code', category: 'docs', lang: 'text' },
  asciidoc: { kind: 'code', category: 'docs', lang: 'text' },
  diff: { kind: 'code', category: 'code', lang: 'diff' },
  patch: { kind: 'code', category: 'code', lang: 'diff' },
  log: { kind: 'code', category: 'other', lang: 'text' },
  txt: { kind: 'code', category: 'docs', lang: 'text' },
  text: { kind: 'code', category: 'docs', lang: 'text' },

  docx: { kind: 'docx', category: 'docs' },
  doc: { kind: 'nopreview', category: 'docs' },
  odt: { kind: 'nopreview', category: 'docs' },
  rtf: { kind: 'code', category: 'docs', lang: 'text' },
  pdf: { kind: 'pdf', category: 'docs' },
  pages: { kind: 'nopreview', category: 'docs' },
  wpd: { kind: 'nopreview', category: 'docs' },

  xlsx: { kind: 'sheet', category: 'spreadsheet' },
  xls: { kind: 'sheet', category: 'spreadsheet' },
  xlsm: { kind: 'sheet', category: 'spreadsheet' },
  xlsb: { kind: 'sheet', category: 'spreadsheet' },
  ods: { kind: 'sheet', category: 'spreadsheet' },
  numbers: { kind: 'nopreview', category: 'spreadsheet' },

  pptx: { kind: 'nopreview', category: 'presentation' },
  ppt: { kind: 'nopreview', category: 'presentation' },
  ppsx: { kind: 'nopreview', category: 'presentation' },
  pps: { kind: 'nopreview', category: 'presentation' },
  odp: { kind: 'nopreview', category: 'presentation' },
  keynote: { kind: 'nopreview', category: 'presentation' },

  epub: { kind: 'archive', category: 'ebook' },
  mobi: { kind: 'nopreview', category: 'ebook' },
  azw: { kind: 'nopreview', category: 'ebook' },
  azw3: { kind: 'nopreview', category: 'ebook' },
  fb2: { kind: 'code', category: 'ebook', lang: 'xml' },
  djvu: { kind: 'nopreview', category: 'ebook' },
  djv: { kind: 'nopreview', category: 'ebook' },

  png: { kind: 'image', category: 'image' },
  jpg: { kind: 'image', category: 'image' },
  jpeg: { kind: 'image', category: 'image' },
  gif: { kind: 'image', category: 'image' },
  webp: { kind: 'image', category: 'image' },
  bmp: { kind: 'image', category: 'image' },
  ico: { kind: 'image', category: 'image' },
  avif: { kind: 'image', category: 'image' },
  svg: { kind: 'image', category: 'image' },
  tiff: { kind: 'image', category: 'image' },
  tif: { kind: 'image', category: 'image' },
  heic: { kind: 'image', category: 'image' },
  heif: { kind: 'image', category: 'image' },
  cr2: { kind: 'nopreview', category: 'image' },
  nef: { kind: 'nopreview', category: 'image' },
  arw: { kind: 'nopreview', category: 'image' },
  dng: { kind: 'nopreview', category: 'image' },
  raf: { kind: 'nopreview', category: 'image' },
  orf: { kind: 'nopreview', category: 'image' },
  rw2: { kind: 'nopreview', category: 'image' },

  psd: { kind: 'nopreview', category: 'design' },
  ai: { kind: 'nopreview', category: 'design' },
  eps: { kind: 'nopreview', category: 'design' },
  sketch: { kind: 'nopreview', category: 'design' },
  fig: { kind: 'nopreview', category: 'design' },
  xd: { kind: 'nopreview', category: 'design' },
  indd: { kind: 'nopreview', category: 'design' },

  mp3: { kind: 'audio', category: 'audio' },
  wav: { kind: 'audio', category: 'audio' },
  ogg: { kind: 'audio', category: 'audio' },
  oga: { kind: 'audio', category: 'audio' },
  m4a: { kind: 'audio', category: 'audio' },
  aac: { kind: 'audio', category: 'audio' },
  flac: { kind: 'audio', category: 'audio' },
  opus: { kind: 'audio', category: 'audio' },
  weba: { kind: 'audio', category: 'audio' },
  wma: { kind: 'audio', category: 'audio' },
  aiff: { kind: 'audio', category: 'audio' },
  aif: { kind: 'audio', category: 'audio' },
  amr: { kind: 'audio', category: 'audio' },
  mid: { kind: 'nopreview', category: 'audio' },
  midi: { kind: 'nopreview', category: 'audio' },

  mp4: { kind: 'video', category: 'video' },
  m4v: { kind: 'video', category: 'video' },
  webm: { kind: 'video', category: 'video' },
  ogv: { kind: 'video', category: 'video' },
  mov: { kind: 'video', category: 'video' },
  mkv: { kind: 'video', category: 'video' },
  avi: { kind: 'video', category: 'video' },
  flv: { kind: 'video', category: 'video' },
  wmv: { kind: 'video', category: 'video' },
  mpg: { kind: 'video', category: 'video' },
  mpeg: { kind: 'video', category: 'video' },
  '3gp': { kind: 'video', category: 'video' },
  '3g2': { kind: 'video', category: 'video' },
  m2ts: { kind: 'video', category: 'video' },
  vob: { kind: 'video', category: 'video' },

  zip: { kind: 'archive', category: 'archive' },
  jar: { kind: 'archive', category: 'archive' },
  war: { kind: 'archive', category: 'archive' },
  ear: { kind: 'archive', category: 'archive' },
  aar: { kind: 'archive', category: 'archive' },
  apk: { kind: 'archive', category: 'package' },
  kmz: { kind: 'archive', category: 'data' },
  rar: { kind: 'nopreview', category: 'archive' },
  '7z': { kind: 'nopreview', category: 'archive' },
  tar: { kind: 'nopreview', category: 'archive' },
  gz: { kind: 'nopreview', category: 'archive' },
  tgz: { kind: 'nopreview', category: 'archive' },
  bz2: { kind: 'nopreview', category: 'archive' },
  xz: { kind: 'nopreview', category: 'archive' },
  zst: { kind: 'nopreview', category: 'archive' },
  iso: { kind: 'nopreview', category: 'archive' },
  cab: { kind: 'nopreview', category: 'archive' },

  dmg: { kind: 'nopreview', category: 'package' },
  pkg: { kind: 'nopreview', category: 'package' },
  deb: { kind: 'nopreview', category: 'package' },
  rpm: { kind: 'nopreview', category: 'package' },
  msi: { kind: 'nopreview', category: 'package' },
  exe: { kind: 'nopreview', category: 'package' },
  appimage: { kind: 'nopreview', category: 'package' },
  wasm: { kind: 'nopreview', category: 'package' },

  ttf: { kind: 'font', category: 'font' },
  otf: { kind: 'font', category: 'font' },
  woff: { kind: 'font', category: 'font' },
  woff2: { kind: 'font', category: 'font' },
  eot: { kind: 'font', category: 'font' },

  obj: { kind: 'nopreview', category: 'cad3d' },
  stl: { kind: 'nopreview', category: 'cad3d' },
  glb: { kind: 'nopreview', category: 'cad3d' },
  gltf: { kind: 'code', category: 'cad3d', lang: 'json' },
  fbx: { kind: 'nopreview', category: 'cad3d' },
  dae: { kind: 'code', category: 'cad3d', lang: 'xml' },
  blend: { kind: 'nopreview', category: 'cad3d' },
  '3ds': { kind: 'nopreview', category: 'cad3d' },
  ply: { kind: 'nopreview', category: 'cad3d' },
  skp: { kind: 'nopreview', category: 'cad3d' },
  dwg: { kind: 'nopreview', category: 'cad3d' },
  dxf: { kind: 'nopreview', category: 'cad3d' },
  step: { kind: 'nopreview', category: 'cad3d' },
  stp: { kind: 'nopreview', category: 'cad3d' },
  iges: { kind: 'nopreview', category: 'cad3d' },
  igs: { kind: 'nopreview', category: 'cad3d' },

  shp: { kind: 'nopreview', category: 'data' },
  shx: { kind: 'nopreview', category: 'data' },
  dbf: { kind: 'nopreview', category: 'data' },

  sqlite: { kind: 'nopreview', category: 'database' },
  sqlite3: { kind: 'nopreview', category: 'database' },
  db: { kind: 'nopreview', category: 'database' },
  mdb: { kind: 'nopreview', category: 'database' },
  accdb: { kind: 'nopreview', category: 'database' },
  parquet: { kind: 'nopreview', category: 'database' },
  avro: { kind: 'nopreview', category: 'database' },
  orc: { kind: 'nopreview', category: 'database' },

  pem: { kind: 'code', category: 'cert', lang: 'text' },
  crt: { kind: 'code', category: 'cert', lang: 'text' },
  cer: { kind: 'code', category: 'cert', lang: 'text' },
  key: { kind: 'code', category: 'cert', lang: 'text' },
  pub: { kind: 'code', category: 'cert', lang: 'text' },
  csr: { kind: 'code', category: 'cert', lang: 'text' },
  p7b: { kind: 'code', category: 'cert', lang: 'text' },
  p7c: { kind: 'code', category: 'cert', lang: 'text' },
  pfx: { kind: 'nopreview', category: 'cert' },
  p12: { kind: 'nopreview', category: 'cert' },
  jks: { kind: 'nopreview', category: 'cert' },

  eml: { kind: 'email', category: 'email' },
  msg: { kind: 'nopreview', category: 'email' },
  mbox: { kind: 'code', category: 'email', lang: 'text' },
};

export function getExt(name) {
  const i = name.lastIndexOf('.');
  return i === -1 ? '' : name.slice(i + 1).toLowerCase();
}

export function classify(filename) {
  const lower = filename.toLowerCase().trim();
  if (FILENAME_OVERRIDES[lower]) return FILENAME_OVERRIDES[lower];
  const ext = getExt(filename);
  if (EXT_MAP[ext]) return { ...EXT_MAP[ext], ext };
  return { kind: 'unknown', category: 'other', ext };
}

export function formatSize(n) {
  if (n < 1024) return `${n} B`;
  if (n < 1024 ** 2) return `${(n / 1024).toFixed(1)} KB`;
  if (n < 1024 ** 3) return `${(n / 1024 ** 2).toFixed(1)} MB`;
  return `${(n / 1024 ** 3).toFixed(2)} GB`;
}

export function buildHexDump(buf) {
  const bytes = new Uint8Array(buf);
  const rows = [];
  for (let i = 0; i < bytes.length; i += 16) {
    const chunk = bytes.slice(i, i + 16);
    const hex = Array.from(chunk).map((b) => b.toString(16).padStart(2, '0')).join(' ');
    const ascii = Array.from(chunk).map((b) => (b >= 32 && b < 127 ? String.fromCharCode(b) : '.')).join('');
    rows.push({ offset: i.toString(16).padStart(6, '0'), hex, ascii });
  }
  return rows;
}

export function looksLikeText(arrayBuffer) {
  const sampleLen = Math.min(arrayBuffer.byteLength, 2000);
  if (sampleLen === 0) return true;
  const bytes = new Uint8Array(arrayBuffer, 0, sampleLen);
  let control = 0;
  for (let i = 0; i < bytes.length; i++) {
    const b = bytes[i];
    if (b === 9 || b === 10 || b === 13) continue;
    if (b < 32 || b === 127) control++;
  }
  return control / sampleLen < 0.05;
}

export const genId = () =>
  (typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2));
